In [1]:
import pandas as pd
import numpy as np

In [2]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
print(mylist)

['a', 'b', 'c', 'e', 'd', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

In [3]:
lst = pd.DataFrame(mylist)

In [4]:
lst.head()

   0
0  a
1  b
2  c
3  e
4  d

In [5]:
series = pd.Series(mylist)

In [6]:
series

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [7]:
lst

    0
0   a
1   b
2   c
3   e
4   d
5   f
6   g
7   h
8   i
9   j
10  k
11  l
12  m
13  n
14  o
15  p
16  q
17  r
18  s
19  t
20  u
21  v
22  w
23  x
24  y
25  z

In [8]:
#  How to convert the index of a series into a column of a dataframe?
import numpy as np
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
(ser.index)

Index(['a', 'b', 'c', 'e', 'd', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
       'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
      dtype='object')

In [9]:
df = pd.DataFrame()

In [10]:
df['col1'] = ser.index

In [11]:
ser.reset_index()

   index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

In [12]:
ser.to_frame().reset_index()

   index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

In [13]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

In [14]:
ser2

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int64

In [15]:
df = pd.concat([ser1,ser2],axis=1)

In [16]:
df

    0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25

In [17]:
df = pd.DataFrame({'col1':ser1,'col2':ser2})

In [18]:
df

   col1  col2
0     a     0
1     b     1
2     c     2
3     e     3
4     d     4
5     f     5
6     g     6
7     h     7
8     i     8
9     j     9
10    k    10
11    l    11
12    m    12
13    n    13
14    o    14
15    p    15
16    q    16
17    r    17
18    s    18
19    t    19
20    u    20
21    v    21
22    w    22
23    x    23
24    y    24
25    z    25

In [19]:
# 5
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

In [20]:
ser.name ='cnt'

In [21]:
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: cnt, dtype: object

In [22]:
# 6
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [23]:
lst1 = list(ser1.values)
lst2 = list(ser2.values)

In [24]:
ans =[]
for i in lst1:
  if i not in lst2:
    ans.append(i)
ser = pd.Series(ans)

In [25]:
ser=ser.to_frame(name='temp')

In [26]:
ser.index.name='index'

In [27]:
ser

       temp
index
0         1
1         2
2         3

In [28]:
ans

[np.int64(1), np.int64(2), np.int64(3)]

In [29]:
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [30]:
~ser1.isin(ser2)

0     True
1     True
2     True
3    False
4    False
dtype: bool

In [31]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [32]:
print(ser1[~ser1.isin(ser2)])
print(ser2[~ser2.isin(ser1)])
pd.concat([ser1[~ser1.isin(ser2)],ser2[~ser2.isin(ser1)]],axis=0).reset_index(drop=True)

0    1
1    2
2    3
dtype: int64
2    6
3    7
4    8
dtype: int64

0    1
1    2
2    3
3    6
4    7
5    8
dtype: int64

In [33]:
np.intersect1d(ser1,ser2)

array([4, 5])

In [34]:
ser_u = pd.Series(np.union1d(ser1, ser2)) # union
ser_i = pd.Series(np.intersect1d(ser1, ser2)) # intersect
print(ser_u[~ser_u.isin(ser_i)])

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [35]:
print(ser1.isin(ser2))
print(~ser1.isin(ser2))

0    False
1    False
2    False
3     True
4     True
dtype: bool
0     True
1     True
2     True
3    False
4    False
dtype: bool

In [36]:
# 8 need to get percentiles

In [37]:
ser = pd.Series(np.random.normal(10, 5, 25))

In [38]:
ser

0     15.984778
1      5.067567
2      8.068687
3     16.417252
4     19.349166
5     12.389521
6     10.932215
7      2.227343
8      6.811521
9      4.332057
10    12.347270
11     7.269823
12     2.658854
13     9.881779
14     5.554652
15     2.703676
16    16.193056
17    11.019292
18     4.740859
19    20.353112
20    18.945732
21     7.206055
22     5.049204
23     7.221315
24     8.544687
dtype: float64

In [39]:
ser.quantile(0.75)

np.float64(12.389521286771439)

In [40]:
ser.median()

8.068687379138728

In [41]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

In [42]:
ser

0     d
1     h
2     e
3     f
4     b
5     f
6     d
7     h
8     d
9     f
10    d
11    b
12    h
13    a
14    d
15    g
16    g
17    d
18    b
19    g
20    g
21    f
22    c
23    d
24    f
25    c
26    a
27    f
28    b
29    g
dtype: object

In [43]:
ser.value_counts().index[:2]

Index(['d', 'f'], dtype='object')

In [44]:
ser[~ser.isin(ser.value_counts().index[:2])]='other'

In [45]:
ser

0         d
1     other
2     other
3         f
4     other
5         f
6         d
7     other
8         d
9         f
10        d
11    other
12    other
13    other
14        d
15    other
16    other
17        d
18    other
19    other
20    other
21        f
22    other
23        d
24        f
25    other
26    other
27        f
28    other
29    other
dtype: object

In [46]:
# 11

In [47]:
ser = pd.Series(np.random.random(20))

In [48]:
ser

0     0.870082
1     0.365878
2     0.696062
3     0.546991
4     0.963838
5     0.488517
6     0.280802
7     0.896511
8     0.707581
9     0.524403
10    0.275843
11    0.839247
12    0.574833
13    0.000378
14    0.133034
15    0.888933
16    0.006348
17    0.666105
18    0.324056
19    0.123736
dtype: float64

In [52]:
result = pd.qcut(ser,q=10,labels=['1','2','3','4','5','6','7','8','9','10'])

In [56]:
result

0      9
1      4
2      7
3      6
4     10
5      5
6      3
7     10
8      8
9      5
10     3
11     8
12     6
13     1
14     2
15     9
16     1
17     7
18     4
19     2
dtype: category
Categories (10, object): ['1' < '2' < '3' < '4' ... '7' < '8' < '9' < '10']

In [57]:
# 12

In [58]:
ser = pd.Series(np.random.randint(1, 10, 35))

In [59]:
ser

0     2
1     9
2     6
3     3
4     2
5     3
6     6
7     7
8     5
9     2
10    8
11    9
12    8
13    6
14    5
15    7
16    6
17    2
18    7
19    3
20    5
21    7
22    6
23    9
24    5
25    2
26    5
27    2
28    3
29    5
30    8
31    7
32    5
33    6
34    2
dtype: int64

In [63]:
np.reshape(ser.values,(7,5))

array([[2, 9, 6, 3, 2],
       [3, 6, 7, 5, 2],
       [8, 9, 8, 6, 5],
       [7, 6, 2, 7, 3],
       [5, 7, 6, 9, 5],
       [2, 5, 2, 3, 5],
       [8, 7, 5, 6, 2]])

In [64]:
# 13

In [67]:
ser = pd.Series(np.random.randint(1, 10, 15))

In [68]:
ser

0     1
1     2
2     9
3     6
4     3
5     1
6     5
7     9
8     4
9     5
10    6
11    8
12    5
13    6
14    6
dtype: int64

In [79]:
ser[ser%3==0]

2     9
3     6
4     3
7     9
10    6
13    6
14    6
dtype: int64

In [81]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

In [82]:
ser[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

In [83]:
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [84]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

In [85]:
print(ser1)
print(ser2)

0    0
1    1
2    2
3    3
4    4
dtype: int64
0    a
1    b
2    c
3    d
4    e
dtype: object

In [87]:
pd.concat([ser1,ser2],axis=1)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [91]:
pd.concat([ser1,ser2],axis=0).reset_index()

   index  0
0      0  0
1      1  1
2      2  2
3      3  3
4      4  4
5      0  a
6      1  b
7      2  c
8      3  d
9      4  e

In [92]:
# 16

In [93]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

In [97]:
ser1.isin(ser2)

0     True
1    False
2    False
3    False
4     True
5     True
6    False
7    False
8     True
dtype: bool

In [99]:
# 16 if i know the value how to get index

In [132]:
[int(np.where(ser1 ==i)[0][0]) for i in ser2]

[5, 4, 0, 8]

In [133]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

In [134]:
print(truth)
print(pred)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
0    0.402426
1    1.775674
2    2.606089
3    3.500508
4    4.825173
5    5.682793
6    6.964344
7    7.231237
8    8.333028
9    9.015814
dtype: float64

In [141]:
np.mean((pred-truth)**2)

np.float64(0.3623174454615319)

In [139]:
truth.shape[0]

10

In [157]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [155]:
for i in range(len(ser)):
  ser[i]=ser[i].capitalize()

In [156]:
ser

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [159]:
ser[i]

In [160]:
# 17 done 18 onwards remaining