In [1]:
import pandas as pd
import numpy as np

In [2]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
print(mylist)

['a', 'b', 'c', 'e', 'd', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

In [3]:
lst = pd.DataFrame(mylist)

In [4]:
lst.head()

   0
0  a
1  b
2  c
3  e
4  d

In [5]:
series = pd.Series(mylist)

In [6]:
series

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [7]:
lst

    0
0   a
1   b
2   c
3   e
4   d
5   f
6   g
7   h
8   i
9   j
10  k
11  l
12  m
13  n
14  o
15  p
16  q
17  r
18  s
19  t
20  u
21  v
22  w
23  x
24  y
25  z

In [8]:
#  How to convert the index of a series into a column of a dataframe?
import numpy as np
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
(ser.index)

Index(['a', 'b', 'c', 'e', 'd', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
       'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
      dtype='object')

In [9]:
df = pd.DataFrame()

In [10]:
df['col1'] = ser.index

In [11]:
ser.reset_index()

   index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

In [12]:
ser.to_frame().reset_index()

   index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

In [13]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

In [14]:
ser2

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int64

In [15]:
df = pd.concat([ser1,ser2],axis=1)

In [16]:
df

    0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25

In [17]:
df = pd.DataFrame({'col1':ser1,'col2':ser2})

In [18]:
df

   col1  col2
0     a     0
1     b     1
2     c     2
3     e     3
4     d     4
5     f     5
6     g     6
7     h     7
8     i     8
9     j     9
10    k    10
11    l    11
12    m    12
13    n    13
14    o    14
15    p    15
16    q    16
17    r    17
18    s    18
19    t    19
20    u    20
21    v    21
22    w    22
23    x    23
24    y    24
25    z    25

In [27]:
# 5
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

In [28]:
ser.name ='cnt'

In [29]:
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: cnt, dtype: object

In [55]:
# 6
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [37]:
lst1 = list(ser1.values)
lst2 = list(ser2.values)

In [42]:
ans =[]
for i in lst1:
  if i not in lst2:
    ans.append(i)
ser = pd.Series(ans)

In [48]:
ser=ser.to_frame(name='temp')

In [46]:
ser.index.name='index'

In [49]:
ser

       temp
index
0         1
1         2
2         3

before 1
before 2
before 3
before 4
before 5
inside 5

In [63]:
ans

[5]

In [69]:
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [70]:
~ser1.isin(ser2)

0     True
1     True
2     True
3    False
4    False
dtype: bool

In [72]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [80]:
print(ser1[~ser1.isin(ser2)])
print(ser2[~ser2.isin(ser1)])
pd.concat([ser1[~ser1.isin(ser2)],ser2[~ser2.isin(ser1)]],axis=0).reset_index(drop=True)

0    1
1    2
2    3
dtype: int64
2    6
3    7
4    8
dtype: int64

0    1
1    2
2    3
3    6
4    7
5    8
dtype: int64

In [82]:
np.intersect1d(ser1,ser2)

array([4, 5])

In [83]:
ser_u = pd.Series(np.union1d(ser1, ser2)) # union
ser_i = pd.Series(np.intersect1d(ser1, ser2)) # intersect
print(ser_u[~ser_u.isin(ser_i)])

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [86]:
print(ser1.isin(ser2))
print(~ser1.isin(ser2))

0    False
1    False
2    False
3     True
4     True
dtype: bool
0     True
1     True
2     True
3    False
4    False
dtype: bool

In [87]:
# 8 need to get percentiles

In [88]:
ser = pd.Series(np.random.normal(10, 5, 25))

In [89]:
ser

0      4.999619
1      2.175437
2      7.394531
3      4.018205
4      3.466191
5      8.562031
6      7.379372
7     14.043536
8     15.392504
9      9.974842
10    20.266378
11     8.930671
12     9.886655
13     7.686989
14    13.560464
15    11.546753
16    16.523804
17     6.576412
18    13.810504
19     9.714519
20    13.157998
21    12.392633
22     9.508772
23     8.398370
24     9.563490
dtype: float64

In [95]:
ser.quantile(0.75)

np.float64(13.157998459016014)

In [99]:
ser.median()

9.56348963745523

In [100]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

In [101]:
ser

0     b
1     d
2     c
3     e
4     c
5     e
6     b
7     g
8     d
9     d
10    b
11    a
12    c
13    f
14    a
15    a
16    e
17    e
18    d
19    b
20    d
21    h
22    h
23    c
24    b
25    f
26    a
27    h
28    h
29    e
dtype: object

In [114]:
ser.value_counts().index[:2]

Index(['b', 'd'], dtype='object')

In [117]:
ser[~ser.isin(ser.value_counts().index[:2])]='other'

In [118]:
ser

0         b
1         d
2     other
3     other
4     other
5     other
6         b
7     other
8         d
9         d
10        b
11    other
12    other
13    other
14    other
15    other
16    other
17    other
18        d
19        b
20        d
21    other
22    other
23    other
24        b
25    other
26    other
27    other
28    other
29    other
dtype: object

In [119]:
# 11

In [120]:
ser = pd.Series(np.random.random(20))

In [121]:
ser

0     0.513370
1     0.756303
2     0.504783
3     0.336186
4     0.180554
5     0.952118
6     0.677496
7     0.680904
8     0.268292
9     0.920993
10    0.472902
11    0.299607
12    0.554839
13    0.534741
14    0.745934
15    0.987739
16    0.971968
17    0.361457
18    0.833043
19    0.332781
dtype: float64

In [123]:
ser.groupby()

TypeError: You have to supply one of 'by' and 'level'