In [1]:
import pandas as pd
import numpy as np

In [2]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
print(mylist)

['a', 'b', 'c', 'e', 'd', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

In [3]:
lst = pd.DataFrame(mylist)

In [4]:
lst.head()

   0
0  a
1  b
2  c
3  e
4  d

In [5]:
series = pd.Series(mylist)

In [6]:
series

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [7]:
lst

    0
0   a
1   b
2   c
3   e
4   d
5   f
6   g
7   h
8   i
9   j
10  k
11  l
12  m
13  n
14  o
15  p
16  q
17  r
18  s
19  t
20  u
21  v
22  w
23  x
24  y
25  z

In [8]:
#  How to convert the index of a series into a column of a dataframe?
import numpy as np
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
(ser.index)

Index(['a', 'b', 'c', 'e', 'd', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
       'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
      dtype='object')

In [9]:
df = pd.DataFrame()

In [10]:
df['col1'] = ser.index

In [11]:
ser.reset_index()

   index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

In [12]:
ser.to_frame().reset_index()

   index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

In [13]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

In [14]:
ser2

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int64

In [15]:
df = pd.concat([ser1,ser2],axis=1)

In [16]:
df

    0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25

In [17]:
df = pd.DataFrame({'col1':ser1,'col2':ser2})

In [18]:
df

   col1  col2
0     a     0
1     b     1
2     c     2
3     e     3
4     d     4
5     f     5
6     g     6
7     h     7
8     i     8
9     j     9
10    k    10
11    l    11
12    m    12
13    n    13
14    o    14
15    p    15
16    q    16
17    r    17
18    s    18
19    t    19
20    u    20
21    v    21
22    w    22
23    x    23
24    y    24
25    z    25

In [19]:
# 5
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

In [20]:
ser.name ='cnt'

In [21]:
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: cnt, dtype: object

In [22]:
# 6
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [23]:
lst1 = list(ser1.values)
lst2 = list(ser2.values)

In [24]:
ans =[]
for i in lst1:
  if i not in lst2:
    ans.append(i)
ser = pd.Series(ans)

In [25]:
ser=ser.to_frame(name='temp')

In [26]:
ser.index.name='index'

In [27]:
ser

       temp
index
0         1
1         2
2         3

In [28]:
ans

[np.int64(1), np.int64(2), np.int64(3)]

In [29]:
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [30]:
~ser1.isin(ser2)

0     True
1     True
2     True
3    False
4    False
dtype: bool

In [31]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [32]:
print(ser1[~ser1.isin(ser2)])
print(ser2[~ser2.isin(ser1)])
pd.concat([ser1[~ser1.isin(ser2)],ser2[~ser2.isin(ser1)]],axis=0).reset_index(drop=True)

0    1
1    2
2    3
dtype: int64
2    6
3    7
4    8
dtype: int64

0    1
1    2
2    3
3    6
4    7
5    8
dtype: int64

In [33]:
np.intersect1d(ser1,ser2)

array([4, 5])

In [34]:
ser_u = pd.Series(np.union1d(ser1, ser2)) # union
ser_i = pd.Series(np.intersect1d(ser1, ser2)) # intersect
print(ser_u[~ser_u.isin(ser_i)])

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [35]:
print(ser1.isin(ser2))
print(~ser1.isin(ser2))

0    False
1    False
2    False
3     True
4     True
dtype: bool
0     True
1     True
2     True
3    False
4    False
dtype: bool

In [36]:
# 8 need to get percentiles

In [37]:
ser = pd.Series(np.random.normal(10, 5, 25))

In [38]:
ser

0     14.056600
1      9.711571
2      5.203340
3      2.441092
4     10.752691
5     20.032592
6     13.099178
7     15.366064
8      7.815952
9      8.759634
10    15.918170
11    12.424593
12    11.313526
13    11.986223
14     5.471118
15     4.511134
16    14.347265
17    12.634685
18    13.048962
19    13.653334
20    15.791135
21    12.863853
22    21.153698
23    12.231894
24     7.309316
dtype: float64

In [39]:
ser.quantile(0.75)

np.float64(14.056599704361304)

In [40]:
ser.median()

12.424592855000789

In [41]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

In [42]:
ser

0     e
1     d
2     g
3     g
4     e
5     c
6     d
7     c
8     g
9     c
10    d
11    f
12    g
13    f
14    b
15    a
16    b
17    e
18    f
19    h
20    b
21    h
22    a
23    e
24    e
25    d
26    c
27    b
28    a
29    g
dtype: object

In [43]:
ser.value_counts().index[:2]

Index(['e', 'g'], dtype='object')

In [44]:
ser[~ser.isin(ser.value_counts().index[:2])]='other'

In [45]:
ser

0         e
1     other
2         g
3         g
4         e
5     other
6     other
7     other
8         g
9     other
10    other
11    other
12        g
13    other
14    other
15    other
16    other
17        e
18    other
19    other
20    other
21    other
22    other
23        e
24        e
25    other
26    other
27    other
28    other
29        g
dtype: object

In [46]:
# 11

In [47]:
ser = pd.Series(np.random.random(20))

In [48]:
ser

0     0.068160
1     0.487231
2     0.529889
3     0.119148
4     0.717062
5     0.425298
6     0.893991
7     0.332178
8     0.815730
9     0.615642
10    0.486188
11    0.715074
12    0.767771
13    0.049680
14    0.321005
15    0.719568
16    0.030763
17    0.887656
18    0.867094
19    0.066168
dtype: float64

In [49]:
result = pd.qcut(ser,q=10,labels=['1','2','3','4','5','6','7','8','9','10'])

In [50]:
result

0      2
1      5
2      6
3      3
4      7
5      4
6     10
7      4
8      9
9      6
10     5
11     7
12     8
13     1
14     3
15     8
16     1
17    10
18     9
19     2
dtype: category
Categories (10, object): ['1' < '2' < '3' < '4' ... '7' < '8' < '9' < '10']

In [51]:
# 12

In [52]:
ser = pd.Series(np.random.randint(1, 10, 35))

In [53]:
ser

0     5
1     9
2     4
3     7
4     9
5     2
6     8
7     3
8     3
9     1
10    1
11    6
12    9
13    1
14    5
15    5
16    2
17    1
18    1
19    2
20    5
21    6
22    7
23    1
24    2
25    5
26    3
27    9
28    9
29    3
30    3
31    4
32    9
33    7
34    1
dtype: int64

In [54]:
np.reshape(ser.values,(7,5))

array([[5, 9, 4, 7, 9],
       [2, 8, 3, 3, 1],
       [1, 6, 9, 1, 5],
       [5, 2, 1, 1, 2],
       [5, 6, 7, 1, 2],
       [5, 3, 9, 9, 3],
       [3, 4, 9, 7, 1]])

In [55]:
# 13

In [56]:
ser = pd.Series(np.random.randint(1, 10, 15))

In [57]:
ser

0     6
1     9
2     6
3     9
4     2
5     2
6     9
7     4
8     6
9     1
10    5
11    7
12    2
13    8
14    7
dtype: int64

In [58]:
ser[ser%3==0]

0    6
1    9
2    6
3    9
6    9
8    6
dtype: int64

In [59]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

In [60]:
ser[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

In [61]:
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [62]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

In [63]:
print(ser1)
print(ser2)

0    0
1    1
2    2
3    3
4    4
dtype: int64
0    a
1    b
2    c
3    d
4    e
dtype: object

In [64]:
pd.concat([ser1,ser2],axis=1)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [65]:
pd.concat([ser1,ser2],axis=0).reset_index()

   index  0
0      0  0
1      1  1
2      2  2
3      3  3
4      4  4
5      0  a
6      1  b
7      2  c
8      3  d
9      4  e

In [66]:
# 16

In [67]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

In [68]:
ser1.isin(ser2)

0     True
1    False
2    False
3    False
4     True
5     True
6    False
7    False
8     True
dtype: bool

In [69]:
# 16 if i know the value how to get index

In [70]:
[int(np.where(ser1 ==i)[0][0]) for i in ser2]

[5, 4, 0, 8]

In [71]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

In [72]:
print(truth)
print(pred)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
0    0.267959
1    1.800586
2    2.027236
3    3.257695
4    4.809289
5    5.006907
6    6.698333
7    7.290945
8    8.257629
9    9.491159
dtype: float64

In [73]:
np.mean((pred-truth)**2)

np.float64(0.23148126017197682)

In [74]:
truth.shape[0]

10

In [75]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [76]:
for i in range(len(ser)):
  ser[i]=ser[i].capitalize()

In [77]:
ser

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [78]:
ser[i]

'Ass?'

In [79]:
# 17 done 18 onwards remaining

In [80]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

In [84]:
[int(np.where(ser1==i)[0][0]) for i in ser2]

[5, 4, 0, 8]

In [88]:
[int(np.argwhere(ser1==i)[0][0]) for i in ser2]

[5, 4, 0, 8]

In [91]:
ser2.values.tolist()

[1, 3, 10, 13]

In [94]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [99]:
ser.map(lambda x:x[0].upper()+x[1:])

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [109]:
ser.apply(lambda x : x.title())

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [110]:
ser.apply(lambda x:len(x))

0    3
1    2
2    4
3    4
dtype: int64

In [111]:
for i in range(len(ser)):
  print(i)

0
1
2
3

In [139]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

In [122]:
ser1 = pd.Series(np.nan)

In [134]:
ser1

0   NaN
dtype: float64

In [135]:
ser2 = pd.concat([ser1,ser],axis=0,ignore_index=True)

In [136]:
ser2 = ser2[:8]

In [137]:
ser = ser - ser2

In [138]:
ser

0    NaN
1    NaN
2    1.0
3    1.0
4    1.0
5    1.0
6    0.0
7    2.0
dtype: float64

In [140]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

In [143]:
ser.diff().diff()

0    NaN
1    NaN
2    1.0
3    1.0
4    1.0
5    1.0
6    0.0
7    2.0
dtype: float64