In [ ]:
import pandas as pd
import numpy as np

In [ ]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
print(mylist)

['a', 'b', 'c', 'e', 'd', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

In [ ]:
lst = pd.DataFrame(mylist)

In [ ]:
lst.head()

   0
0  a
1  b
2  c
3  e
4  d

In [ ]:
series = pd.Series(mylist)

In [ ]:
series

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [ ]:
lst

    0
0   a
1   b
2   c
3   e
4   d
5   f
6   g
7   h
8   i
9   j
10  k
11  l
12  m
13  n
14  o
15  p
16  q
17  r
18  s
19  t
20  u
21  v
22  w
23  x
24  y
25  z

In [ ]:
#  How to convert the index of a series into a column of a dataframe?
import numpy as np
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
(ser.index)

Index(['a', 'b', 'c', 'e', 'd', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
       'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
      dtype='object')

In [ ]:
df = pd.DataFrame()

In [ ]:
df['col1'] = ser.index

In [ ]:
ser.reset_index()

   index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

In [ ]:
ser.to_frame().reset_index()

   index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

In [ ]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

In [ ]:
ser2

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int64

In [ ]:
df = pd.concat([ser1,ser2],axis=1)

In [ ]:
df

    0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25

In [ ]:
df = pd.DataFrame({'col1':ser1,'col2':ser2})

In [ ]:
df

   col1  col2
0     a     0
1     b     1
2     c     2
3     e     3
4     d     4
5     f     5
6     g     6
7     h     7
8     i     8
9     j     9
10    k    10
11    l    11
12    m    12
13    n    13
14    o    14
15    p    15
16    q    16
17    r    17
18    s    18
19    t    19
20    u    20
21    v    21
22    w    22
23    x    23
24    y    24
25    z    25

In [ ]:
# 5
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

In [ ]:
ser.name ='cnt'

In [ ]:
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: cnt, dtype: object

In [ ]:
# 6
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [ ]:
lst1 = list(ser1.values)
lst2 = list(ser2.values)

In [ ]:
ans =[]
for i in lst1:
  if i not in lst2:
    ans.append(i)
ser = pd.Series(ans)

In [ ]:
ser=ser.to_frame(name='temp')

In [ ]:
ser.index.name='index'

In [ ]:
ser

       temp
index
0         1
1         2
2         3

In [ ]:
ans

[np.int64(1), np.int64(2), np.int64(3)]

In [ ]:
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [ ]:
~ser1.isin(ser2)

0     True
1     True
2     True
3    False
4    False
dtype: bool

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [ ]:
print(ser1[~ser1.isin(ser2)])
print(ser2[~ser2.isin(ser1)])
pd.concat([ser1[~ser1.isin(ser2)],ser2[~ser2.isin(ser1)]],axis=0).reset_index(drop=True)

0    1
1    2
2    3
dtype: int64
2    6
3    7
4    8
dtype: int64

0    1
1    2
2    3
3    6
4    7
5    8
dtype: int64

In [ ]:
np.intersect1d(ser1,ser2)

array([4, 5])

In [ ]:
ser_u = pd.Series(np.union1d(ser1, ser2)) # union
ser_i = pd.Series(np.intersect1d(ser1, ser2)) # intersect
print(ser_u[~ser_u.isin(ser_i)])

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [ ]:
print(ser1.isin(ser2))
print(~ser1.isin(ser2))

0    False
1    False
2    False
3     True
4     True
dtype: bool
0     True
1     True
2     True
3    False
4    False
dtype: bool

In [ ]:
# 8 need to get percentiles

In [ ]:
ser = pd.Series(np.random.normal(10, 5, 25))

In [ ]:
ser

0     14.056600
1      9.711571
2      5.203340
3      2.441092
4     10.752691
5     20.032592
6     13.099178
7     15.366064
8      7.815952
9      8.759634
10    15.918170
11    12.424593
12    11.313526
13    11.986223
14     5.471118
15     4.511134
16    14.347265
17    12.634685
18    13.048962
19    13.653334
20    15.791135
21    12.863853
22    21.153698
23    12.231894
24     7.309316
dtype: float64

In [ ]:
ser.quantile(0.75)

np.float64(14.056599704361304)

In [ ]:
ser.median()

12.424592855000789

In [ ]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

In [ ]:
ser

0     e
1     d
2     g
3     g
4     e
5     c
6     d
7     c
8     g
9     c
10    d
11    f
12    g
13    f
14    b
15    a
16    b
17    e
18    f
19    h
20    b
21    h
22    a
23    e
24    e
25    d
26    c
27    b
28    a
29    g
dtype: object

In [ ]:
ser.value_counts().index[:2]

Index(['e', 'g'], dtype='object')

In [ ]:
ser[~ser.isin(ser.value_counts().index[:2])]='other'

In [ ]:
ser

0         e
1     other
2         g
3         g
4         e
5     other
6     other
7     other
8         g
9     other
10    other
11    other
12        g
13    other
14    other
15    other
16    other
17        e
18    other
19    other
20    other
21    other
22    other
23        e
24        e
25    other
26    other
27    other
28    other
29        g
dtype: object

In [ ]:
# 11

In [ ]:
ser = pd.Series(np.random.random(20))

In [ ]:
ser

0     0.068160
1     0.487231
2     0.529889
3     0.119148
4     0.717062
5     0.425298
6     0.893991
7     0.332178
8     0.815730
9     0.615642
10    0.486188
11    0.715074
12    0.767771
13    0.049680
14    0.321005
15    0.719568
16    0.030763
17    0.887656
18    0.867094
19    0.066168
dtype: float64

In [ ]:
result = pd.qcut(ser,q=10,labels=['1','2','3','4','5','6','7','8','9','10'])

In [ ]:
result

0      2
1      5
2      6
3      3
4      7
5      4
6     10
7      4
8      9
9      6
10     5
11     7
12     8
13     1
14     3
15     8
16     1
17    10
18     9
19     2
dtype: category
Categories (10, object): ['1' < '2' < '3' < '4' ... '7' < '8' < '9' < '10']

In [ ]:
# 12

In [ ]:
ser = pd.Series(np.random.randint(1, 10, 35))

In [ ]:
ser

0     5
1     9
2     4
3     7
4     9
5     2
6     8
7     3
8     3
9     1
10    1
11    6
12    9
13    1
14    5
15    5
16    2
17    1
18    1
19    2
20    5
21    6
22    7
23    1
24    2
25    5
26    3
27    9
28    9
29    3
30    3
31    4
32    9
33    7
34    1
dtype: int64

In [ ]:
np.reshape(ser.values,(7,5))

array([[5, 9, 4, 7, 9],
       [2, 8, 3, 3, 1],
       [1, 6, 9, 1, 5],
       [5, 2, 1, 1, 2],
       [5, 6, 7, 1, 2],
       [5, 3, 9, 9, 3],
       [3, 4, 9, 7, 1]])

In [ ]:
# 13

In [ ]:
ser = pd.Series(np.random.randint(1, 10, 15))

In [ ]:
ser

0     6
1     9
2     6
3     9
4     2
5     2
6     9
7     4
8     6
9     1
10    5
11    7
12    2
13    8
14    7
dtype: int64

In [ ]:
ser[ser%3==0]

0    6
1    9
2    6
3    9
6    9
8    6
dtype: int64

In [ ]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

In [ ]:
ser[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

In [ ]:
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [ ]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

In [ ]:
print(ser1)
print(ser2)

0    0
1    1
2    2
3    3
4    4
dtype: int64
0    a
1    b
2    c
3    d
4    e
dtype: object

In [ ]:
pd.concat([ser1,ser2],axis=1)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [ ]:
pd.concat([ser1,ser2],axis=0).reset_index()

   index  0
0      0  0
1      1  1
2      2  2
3      3  3
4      4  4
5      0  a
6      1  b
7      2  c
8      3  d
9      4  e

In [ ]:
# 16

In [ ]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

In [ ]:
ser1.isin(ser2)

0     True
1    False
2    False
3    False
4     True
5     True
6    False
7    False
8     True
dtype: bool

In [ ]:
# 16 if i know the value how to get index

In [ ]:
[int(np.where(ser1 ==i)[0][0]) for i in ser2]

[5, 4, 0, 8]

In [ ]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

In [ ]:
print(truth)
print(pred)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
0    0.267959
1    1.800586
2    2.027236
3    3.257695
4    4.809289
5    5.006907
6    6.698333
7    7.290945
8    8.257629
9    9.491159
dtype: float64

In [ ]:
np.mean((pred-truth)**2)

np.float64(0.23148126017197682)

In [ ]:
truth.shape[0]

10

In [ ]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [ ]:
for i in range(len(ser)):
  ser[i]=ser[i].capitalize()

In [ ]:
ser

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [ ]:
ser[i]

'Ass?'

In [ ]:
# 17 done 18 onwards remaining

In [ ]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

In [ ]:
[int(np.where(ser1==i)[0][0]) for i in ser2]

[5, 4, 0, 8]

In [ ]:
[int(np.argwhere(ser1==i)[0][0]) for i in ser2]

[5, 4, 0, 8]

In [ ]:
ser2.values.tolist()

[1, 3, 10, 13]

In [ ]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

In [ ]:
ser.map(lambda x:x[0].upper()+x[1:])

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [ ]:
ser.apply(lambda x : x.title())

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [ ]:
ser.apply(lambda x:len(x))

0    3
1    2
2    4
3    4
dtype: int64

In [ ]:
for i in range(len(ser)):
  print(i)

0
1
2
3

In [ ]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

In [ ]:
ser1 = pd.Series(np.nan)

In [ ]:
ser1

0   NaN
dtype: float64

In [ ]:
ser2 = pd.concat([ser1,ser],axis=0,ignore_index=True)

In [ ]:
ser2 = ser2[:8]

In [ ]:
ser = ser - ser2

In [ ]:
ser

0    NaN
1    NaN
2    1.0
3    1.0
4    1.0
5    1.0
6    0.0
7    2.0
dtype: float64

In [ ]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

In [ ]:
ser.diff().diff()

0    NaN
1    NaN
2    1.0
3    1.0
4    1.0
5    1.0
6    0.0
7    2.0
dtype: float64

In [ ]:
# question 20

In [ ]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

In [ ]:
ser.diff(periods=2)

0     NaN
1     NaN
2     5.0
3     7.0
4     9.0
5    11.0
6    12.0
7    14.0
dtype: float64

In [ ]:
list(ser.diff().diff())

[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]

In [ ]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

In [ ]:
from dateutil.parser import parse

In [ ]:
ser.map(lambda x: parse(x))

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [ ]:
print(pd.to_datetime(ser,format='mixed'))

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [ ]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

In [ ]:
pd.to_datetime(ser)

/tmp/ipykernel_1189/711674579.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(ser)

0   2010-01-01
1   2011-02-01
2   2012-03-01
dtype: datetime64[ns]

In [ ]:
ser.map(lambda x:parse(x))

0   2010-01-01
1   2011-02-01
2   2012-03-01
dtype: datetime64[ns]

In [ ]:
ser

0    Jan 2010
1    Feb 2011
2    Mar 2012
dtype: object

In [ ]:
ser1 = [' 4th']*3

In [ ]:
ser1 = pd.Series(ser1)

In [ ]:
pd.concat([ser,ser1],axis=1)

          0     1
0  Jan 2010   4th
1  Feb 2011   4th
2  Mar 2012   4th

In [ ]:
pd.to_datetime(ser+ser1)

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [ ]:
ser = pd.to_datetime(ser)

/tmp/ipykernel_1189/1484864420.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  ser = pd.to_datetime(ser)

In [ ]:
ser

0   2010-01-01
1   2011-02-01
2   2012-03-01
dtype: datetime64[ns]

In [ ]:
ser.dt.year

0    2010
1    2011
2    2012
dtype: int32

In [ ]:
pd.to_datetime(ser.dt.year.astype('str')+'-'+ser.dt.month.astype('str')+'-4th')

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [ ]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

In [ ]:
cnt = 0
for i in ser:
  if cnt==2:
    break
  print(i)
  cnt +=1

Apple
Orange

In [ ]:
st = 'Apple'
'a'in (st.lower())

True

In [ ]:
alpha = pd.Series(list("aeiou"))
def fun(word):
  cnt = 0
  # print(cnt)
  for i in alpha:
    # print(i)
    # print(word.lower())
    if i in word.lower():
      cnt+=1
      # print(cnt)
  if cnt >=2:
    return True
  return False

In [ ]:
ser.map(lambda x:fun(x))

0     True
1     True
2    False
3    False
4     True
dtype: bool

In [ ]:
temp = np.where(ser.map(lambda x:fun(x))==True)[0]

In [ ]:
ser[np.where(ser.map(lambda x:fun(x))==True)[0]]

0     Apple
1    Orange
4     Money
dtype: object

In [ ]:
ser[ser.map(lambda x:fun(x))]

0     Apple
1    Orange
4     Money
dtype: object

In [ ]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

In [ ]:
emails

0    buying books at amazom.com
1             rameses@egypt.com
2                     matt@t.co
3             narendra@modi.com
dtype: object

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import re

In [ ]:
re.match(pattern,emails[0])

In [ ]:
[re.findall(pattern,email) for email in emails]

['[]', "['rameses@egypt.com']", "['matt@t.co']", "['narendra@modi.com']"]

In [ ]:
ans = []
ans + re.findall(pattern,emails[0])

[]

In [ ]:
for email in emails:
  ans += re.findall(pattern,email)

In [ ]:
ans

['rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']

In [ ]:
extracted = emails.str.extract(pattern)[0]

In [ ]:
pattern = '([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4})'

In [ ]:
extracted

0                  NaN
1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
Name: 0, dtype: object

In [ ]:
extracted.dropna().tolist()

['rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']

In [ ]:
bool(re.match(pattern,emails[0]))

False

In [ ]:
emails.str.findall(pattern,flags=re.IGNORECASE).dropna()

0                     []
1    [rameses@egypt.com]
2            [matt@t.co]
3    [narendra@modi.com]
dtype: object

In [ ]:
temp = emails.str.extract(pattern).dropna()

In [ ]:
temp

                   0
1  rameses@egypt.com
2          matt@t.co
3  narendra@modi.com

In [ ]:
temp[0].tolist()

['rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']

In [ ]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['carrot', 'apple', 'apple', 'carrot', 'carrot', 'apple', 'apple', 'apple', 'carrot', 'banana']

In [ ]:
df = pd.concat([fruit,weights,weights],axis=1)

In [ ]:
df

        0     1     2
0  carrot   1.0   1.0
1   apple   2.0   2.0
2   apple   3.0   3.0
3  carrot   4.0   4.0
4  carrot   5.0   5.0
5   apple   6.0   6.0
6   apple   7.0   7.0
7   apple   8.0   8.0
8  carrot   9.0   9.0
9  banana  10.0  10.0

In [ ]:
df.groupby(0).mean()

            1      2
0
apple    5.20   5.20
banana  10.00  10.00
carrot   4.75   4.75

In [ ]:
weights.groupby(fruit).mean()

apple      5.20
banana    10.00
carrot     4.75
dtype: float64

In [6]:
import pandas as pd
import numpy as np

In [ ]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
weights.groupby(fruit).mean()

apple     5.333333
banana    7.500000
carrot    4.000000
dtype: float64

27. How to compute the euclidean distance between two series?

In [ ]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
np.sqrt(np.sum((p-q)**2))

np.float64(18.16590212458495)

In [ ]:
sum((p-q)**2)

330

How to find all the local maxima (or peaks) in a numeric series?

In [ ]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

In [ ]:
n = ser.shape[0]

In [ ]:
ans = []
for i in range(n-1):
  if i==0:
    continue
  if ser[i]>ser[i-1] and ser[i]>ser[i+1]:
    ans.append(i)

In [ ]:
ans

[1, 5, 7]

In [ ]:
ser[ans]

1    10
5    10
7     7
dtype: int64

In [7]:
my_str = 'dbc deb abed gade'

In [8]:
my_str.replace(' ','')

'dbcdebabedgade'

In [9]:
# how to find the most frequient character

In [10]:
df = pd.Series(list(my_str.replace(' ','')))

In [11]:
df.value_counts().idxmax()

'd'

In [14]:
df.value_counts().index[0]

'd'

In [16]:
my_str.replace(' ',df.value_counts().index[-1])

'dbcgdebgabedggade'

30. How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?

In [22]:
pd.date_range(start='2000-01-01',periods=10,freq='W-SAT')

DatetimeIndex(['2000-01-01', '2000-01-08', '2000-01-15', '2000-01-22',
               '2000-01-29', '2000-02-05', '2000-02-12', '2000-02-19',
               '2000-02-26', '2000-03-04'],
              dtype='datetime64[ns]', freq='W-SAT')

In [20]:
pd.Timestamp('2000-01-01').day_name()

'Saturday'

In [23]:
pd.Series(np.random.randint(1,10,10),pd.date_range('2000-01-01',periods=10,freq='W-SAT'))

2000-01-01    6
2000-01-08    9
2000-01-15    8
2000-01-22    1
2000-01-29    6
2000-02-05    1
2000-02-12    1
2000-02-19    1
2000-02-26    1
2000-03-04    4
Freq: W-SAT, dtype: int64

31. How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?

In [24]:
import numpy as np
import pandas as pd
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64

In [29]:
ser.sort_index().values

array([ 1., 10.,  3., nan])

In [34]:
ser['2000-01-08']

np.float64(nan)

In [31]:
ser.shape[0]

4

In [37]:
prev = 0
for i in ser.sort_index():
  print(i)

1.0
10.0
3.0
nan

In [38]:
ser = ser.sort_index()

In [39]:
ser

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64

In [46]:
ser.index

DatetimeIndex(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08'], dtype='datetime64[ns]', freq=None)

In [47]:
for i in ser.index:
  print(i)

2000-01-01 00:00:00
2000-01-03 00:00:00
2000-01-06 00:00:00
2000-01-08 00:00:00

In [59]:
prev = 0
for i in ser.index:
  print(i)
  if pd.isna(ser[i]):
    ser[i] = prev
  prev = ser[i]

2000-01-01 00:00:00
2000-01-03 00:00:00
2000-01-06 00:00:00
2000-01-08 00:00:00

In [60]:
ser

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     3.0
dtype: float64

In [61]:
ser

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     3.0
dtype: float64

In [67]:
ser.resample('D').ffill()

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

In [68]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

In [77]:
ser.autocorr(3)

np.float64(-0.20031696368575033)

In [78]:
ser

0     -5.981746
1      3.612333
2     -9.418385
3     23.640731
4      9.997814
5      2.105337
6     -5.512391
7     -0.247219
8     12.594811
9      5.368015
10    24.241779
11    -4.018853
12    13.650066
13    -6.480834
14    16.858277
15    19.618260
16     9.729180
17    23.382374
18    27.974102
19    15.499099
dtype: float64

In [79]:
ser.autocorr(1)

np.float64(0.04103362375735287)

In [83]:
ans = []
for i in range(1,11):
  ans +=[ser.autocorr(i).round(2)]

In [85]:
np.argmax(ans)

np.int64(6)

In [86]:
ans

[np.float64(0.04),
 np.float64(0.29),
 np.float64(-0.2),
 np.float64(0.1),
 np.float64(0.23),
 np.float64(0.15),
 np.float64(0.49),
 np.float64(-0.18),
 np.float64(0.23),
 np.float64(-0.35)]

In [90]:
df = pd.read_csv('/content/sample_data/mnist_test.csv')

In [96]:
df.iloc[3:4]

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [97]:
df[df.index%50==0]

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
150,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
200,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9750,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9800,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9850,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9900,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9950,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [100]:
df1 = pd.read_csv('/content/sample_data/mnist_test.csv',chunksize=50)

In [102]:
for chunk in df1:
  print(chunk)

Streaming output truncated to the last 5000 lines.
7637  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
7638  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
7639  9  0    0    0    0    0    0    0    0    0  ...      0      0      0
7640  9  0    0    0    0    0    0    0    0    0  ...      0      0      0
7641  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7642  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
7643  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
7644  7  0    0    0    0    0    0    0    0    0  ...      0      0      0
7645  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
7646  7  0    0    0    0    0    0    0    0    0  ...      0      0      0
7647  7  0    0    0    0    0    0    0    0    0  ...      0      0      0
7648  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
7649  7  0    0    0    0    0    0    0    0    0  ...      0      0      0

      0.661  0.662  0.663  0.664  0.665  0.666  0.667
7600      0      0      0      0      0      0      0
7601      0      0      0      0      0      0      0
7602      0      0      0      0      0      0      0
7603      0      0      0      0      0      0      0
7604      0      0      0      0      0      0      0
7605      0      0      0      0      0      0      0
7606      0      0      0      0      0      0      0
7607      0      0      0      0      0      0      0
7608      0      0      0      0      0      0      0
7609      0      0      0      0      0      0      0
7610      0      0      0      0      0      0      0
7611      0      0      0      0      0      0      0
7612      0      0      0      0      0      0      0
7613      0      0      0      0      0      0      0
7614      0      0      0      0      0      0      0
7615      0      0      0      0      0      0      0
7616      0      0      0      0      0      0      0
7617      0      0      0      0      0      0      0
7618      0      0      0      0      0      0      0
7619      0      0      0      0      0      0      0
7620      0      0      0      0      0      0      0
7621      0      0      0      0      0      0      0
7622      0      0      0      0      0      0      0
7623      0      0      0      0      0      0      0
7624      0      0      0      0      0      0      0
7625      0      0      0      0      0      0      0
7626      0      0      0      0      0      0      0
7627      0      0      0      0      0      0      0
7628      0      0      0      0      0      0      0
7629      0      0      0      0      0      0      0
7630      0      0      0      0      0      0      0
7631      0      0      0      0      0      0      0
7632      0      0      0      0      0      0      0
7633      0      0      0      0      0      0      0
7634      0      0      0      0      0      0      0
7635      0      0      0      0      0      0      0
7636      0      0      0      0      0      0      0
7637      0      0      0      0      0      0      0
7638      0      0      0      0      0      0      0
7639      0      0      0      0      0      0      0
7640      0      0      0      0      0      0      0
7641      0      0      0      0      0      0      0
7642      0      0      0      0      0      0      0
7643      0      0      0      0      0      0      0
7644      0      0      0      0      0      0      0
7645      0      0      0      0      0      0      0
7646      0      0      0      0      0      0      0
7647      0      0      0      0      0      0      0
7648      0      0      0      0      0      0      0
7649      0      0      0      0      0      0      0

[50 rows x 785 columns]
      7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
7650  9  0    0    0    0    0    0    0    0    0  ...      0      0      0
7651  9  0    0    0    0    0    0    0    0    0  ...      0      0      0
7652  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
7653  7  0    0    0    0    0    0    0    0    0  ...      0      0      0
7654  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
7655  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
7656  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
7657  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
7658  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
7659  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7660  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
7661  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
7662  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7663  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
7664  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
7665  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7666  6  0    0    0    0    0    0    0    0    0  ...      0      0      0
7667  6  0    0    0    0    0    0    0    0    0  ...      0      0      0
7668  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
7669  6  0    0    0    0    0    0    0    0    0  ...      0      0      0
7670  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
7671  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
7672  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
7673  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
7674  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
7675  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
7676  7  0    0    0    0    0    0    0    0    0  ...      0      0      0
7677  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
7678  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
7679  9  0    0    0    0    0    0    0    0    0  ...      0      0      0
7680  6  0    0    0    0    0    0    0    0    0  ...      0      0      0
7681  9  0    0    0    0    0    0    0    0    0  ...      0      0      0
7682  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
7683  6  0    0    0    0    0    0    0    0    0  ...      0      0      0
7684  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
7685  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
7686  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
7687  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
7688  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7689  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
7690  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7691  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
7692  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
7693  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7694  7  0    0    0    0    0    0    0    0    0  ...      0      0      0
7695  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
7696  9  0    0    0    0    0    0    0    0    0  ...      0      0      0
7697  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
7698  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
7699  9  0    0    0    0    0    0    0    0    0  ...      0      0      0

      0.661  0.662  0.663  0.664  0.665  0.666  0.667
7650      0      0      0      0      0      0      0
7651      0      0      0      0      0      0      0
7652      0      0      0      0      0      0      0
7653      0      0      0      0      0      0      0
7654      0      0      0      0      0      0      0
7655      0      0      0      0      0      0      0
7656      0      0      0      0      0      0      0
7657      0      0      0      0      0      0      0
7658      0      0      0      0      0      0      0
7659      0      0      0      0      0      0      0
7660      0      0      0      0      0      0      0
7661      0      0      0      0      0      0      0
7662      0      0      0      0      0      0      0
7663      0      0      0      0      0      0      0
7664      0      0      0      0      0      0      0
7665      0      0      0      0      0      0      0
7666      0      0      0      0      0      0      0
7667      0      0      0      0      0      0      0
7668      0      0      0      0      0      0      0
7669      0      0      0      0      0      0      0
7670      0      0      0      0      0      0      0
7671      0      0      0      0      0      0      0
7672      0      0      0      0      0      0      0
7673      0      0      0      0      0      0      0
7674      0      0      0      0      0      0      0
7675      0      0      0      0      0      0      0
7676      0      0      0      0      0      0      0
7677      0      0      0      0      0      0      0
7678      0      0      0      0      0      0      0
7679      0      0      0      0      0      0      0
7680      0      0      0      0      0      0      0
7681      0      0      0      0      0      0      0
7682      0      0      0      0      0      0      0
7683      0      0      0      0      0      0      0
7684      0      0      0      0      0      0      0
7685      0      0      0      0      0      0      0
7686      0      0      0      0      0      0      0
7687      0      0      0      0      0      0      0
7688      0      0      0      0      0      0      0
7689      0      0      0      0      0      0      0
7690      0      0      0      0      0      0      0
7691      0      0      0      0      0      0      0
7692      0      0      0      0      0      0      0
7693      0      0      0      0      0      0      0
7694      0      0      0      0      0      0      0
7695      0      0      0      0      0      0      0
7696      0      0      0      0      0      0      0
7697      0      0      0      0      0      0      0
7698      0      0      0      0      0      0      0
7699      0      0      0      0      0      0      0

[50 rows x 785 columns]
      7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
7700  7  0    0    0    0    0    0    0    0    0  ...      0      0      0
7701  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
7702  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
7703  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
7704  6  0    0    0    0    0    0    0    0    0  ...      0      0      0
7705  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
7706  9  0    0    0    0    0    0    0    0    0  ...      0      0      0
7707  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
7708  6  0    0    0    0    0    0    0    0    0  ...      0      0      0
7709  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
7710  7  0    0    0    0    0    0    0    0    0  ...      0      0      0
7711  6  0    0    0    0    0    0    0    0    0  ...      0      0      0
7712  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7713  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
7714  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
7715  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
7716  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
7717  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7718  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
7719  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7720  6  0    0    0    0    0    0    0    0    0  ...      0      0      0
7721  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
7722  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
7723  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
7724  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
7725  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
7726  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
7727  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
7728  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
7729  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
7730  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
7731  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
7732  6  0    0    0    0    0    0    0    0    0  ...      0      0      0
7733  7  0    0    0    0    0    0    0    0    0  ...      0      0      0
7734  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7735  9  0    0    0    0    0    0    0    0    0  ...      0      0      0
7736  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
7737  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
7738  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
7739  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
7740  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
7741  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
7742  6  0    0    0    0    0    0    0    0    0  ...      0      0      0
7743  7  0    0    0    0    0    0    0    0    0  ...      0      0      0
7744  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7745  9  0    0    0    0    0    0    0    0    0  ...      0      0      0
7746  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
7747  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
7748  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
7749  3  0    0    0    0    0    0    0    0    0  ...      0      0      0

      0.661  0.662  0.663  0.664  0.665  0.666  0.667
7700      0      0      0      0      0      0      0
7701      0      0      0      0      0      0      0
7702      0      0      0      0      0      0      0
7703      0      0      0      0      0      0      0
7704      0      0      0      0      0      0      0
7705      0      0      0      0      0      0      0
7706      0      0      0      0      0      0      0
7707      0      0      0      0      0      0      0
7708      0      0      0      0      0      0      0
7709      0      0      0      0      0      0      0
7710      0      0      0      0      0      0      0
7711      0      0      0      0      0      0      0
7712      0      0      0      0      0      0      0
7713      0      0      0      0      0      0      0
7714      0      0      0      0      0      0      0
7715      0      0      0      0      0      0      0
7716      0      0      0      0      0      0      0
7717      0      0      0      0      0      0      0
7718      0      0      0      0      0      0      0
7719      0      0      0      0      0      0      0
7720      0      0      0      0      0      0      0
7721      0      0      0      0      0      0      0
7722      0      0      0      0      0      0      0
7723      0      0      0      0      0      0      0
7724      0      0      0      0      0      0      0
7725      0      0      0      0      0      0      0
7726      0      0      0      0      0      0      0
7727      0      0      0      0      0      0      0
7728      0      0      0      0      0      0      0
7729      0      0      0      0      0      0      0
7730      0      0      0      0      0      0      0
7731      0      0      0      0      0      0      0
7732      0      0      0      0      0      0      0
7733      0      0      0      0      0      0      0
7734      0      0      0      0      0      0      0
7735      0      0      0      0      0      0      0
7736      0      0      0      0      0      0      0
7737      0      0      0      0      0      0      0
7738      0      0      0      0      0      0      0
7739      0      0      0      0      0      0      0
7740      0      0      0      0      0      0      0
7741      0      0      0      0      0      0      0
7742      0      0      0      0      0      0      0
7743      0      0      0      0      0      0      0
7744      0      0      0      0      0      0      0
7745      0      0      0      0      0      0      0
7746      0      0      0      0      0      0      0
7747      0      0      0      0      0      0      0
7748      0      0      0      0      0      0      0
7749      0      0      0      0      0      0      0

[50 rows x 785 columns]
      7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
7750  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
7751  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
7752  6  0    0    0    0    0    0    0    0    0  ...      0      0      0
7753  7  0    0    0    0    0    0    0    0    0  ...      0      0      0
7754  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7755  9  0    0    0    0    0    0    0    0    0  ...      0      0      0
7756  7  0    0    0    0    0    0    0    0    0  ...      0      0      0
7757  6  0    0    0    0    0    0    0    0    0  ...      0      0      0
7758  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
7759  7  0    0    0    0    0    0    0    0    0  ...      0      0      0
7760  6  0    0    0    0    0    0    0    0    0  ...      0      0      0
7761  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
7762  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
7763  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
7764  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7765  7  0    0    0    0    0    0    0    0    0  ...      0      0      0
7766  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7767  6  0    0    0    0    0    0    0    0    0  ...      0      0      0
7768  9  0    0    0    0    0    0    0    0    0  ...      0      0      0
7769  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7770  3  0    0    0    0    0    0    0    0    0  ...      0      0      0
7771  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
7772  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
7773  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7774  4  0    0    0    0    0    0    0    0    0  ...      0      0      0
7775  8  0    0    0    0    0    0    0    0    0  ...      0      0      0
7776  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
7777  6  0    0    0    0    0    0    0    0    0  ...      0      0      0
7778  5  0    0    0    0    0    0    0    0    0  ...      0      0      0
7779  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
7780  2  0    0    0    0    0    0    0    0    0  ...      0      0      0
7781  0  0    0    0    0    0    0    0    0    0  ...      0      0      0
7782  1  0    0    0    0    0    0    0    0    0  ...      0      0      0
7783  1  0    0    0    0    0    0    0    0    0  ...      0      0      0

In [104]:
[chunk.iloc[0] for chunk in df1]

[]

In [106]:
pd.concat([chunk.iloc[[0]] for chunk in df1], axis=1).T

ValueError: No objects to concatenate