In [1]:
import pandas as pd
import numpy as np

In [2]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
print(mylist)

['a', 'b', 'c', 'e', 'd', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

In [3]:
lst = pd.DataFrame(mylist)

In [5]:
lst.head()

   0
0  a
1  b
2  c
3  e
4  d

In [6]:
series = pd.Series(mylist)

In [7]:
series

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [8]:
lst

    0
0   a
1   b
2   c
3   e
4   d
5   f
6   g
7   h
8   i
9   j
10  k
11  l
12  m
13  n
14  o
15  p
16  q
17  r
18  s
19  t
20  u
21  v
22  w
23  x
24  y
25  z

In [13]:
#  How to convert the index of a series into a column of a dataframe?
import numpy as np
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
(ser.index)

pandas.core.indexes.base.Index

In [14]:
df = pd.DataFrame()

In [18]:
df['col1'] = ser.index

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

In [28]:
ser.reset_index()

   index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

In [27]:
ser.to_frame().reset_index()

   index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

In [29]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

In [32]:
ser2

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int64

In [33]:
df = pd.concat([ser1,ser2],axis=1)

In [34]:
df

    0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25

In [35]:
df = pd.DataFrame({'col1':ser1,'col2':ser2})

In [36]:
df

   col1  col2
0     a     0
1     b     1
2     c     2
3     e     3
4     d     4
5     f     5
6     g     6
7     h     7
8     i     8
9     j     9
10    k    10
11    l    11
12    m    12
13    n    13
14    o    14
15    p    15
16    q    16
17    r    17
18    s    18
19    t    19
20    u    20
21    v    21
22    w    22
23    x    23
24    y    24
25    z    25